version: '3.7'

services:
    loot-aspnet-dev:
        build:
            context: ./wesplitlootapi
            dockerfile: Dockerfile
        environment:
        ports: 
            - "5000:80"
        volumes:
            - ./wesplitlootapi/ClientApp:/app/ClientApp
    loot-vue:
        build:
            context: .
            dockerfile: docker/development/vuejs/Dockerfile
        volumes:
            - ./frontend:/app/src
            - ./wesplitlootapi/ClientApp:/app/backend/src/ClientApp
        depends_on: 
            - loot--aspnet-dev
